#!/usr/bin/env ruby
# frozen_string_literal: true

Signal.trap("INT") { exit 1 }

require_relative "../lib/artifactory/gem_import"
require_relative "../lib/artifactory/gem_import/cli"

begin
  Artifactory::GemImport::Cli.start(ARGV)
rescue Artifactory::GemImport::Error => err
  abort "ERROR: #{err}"
end
